Arev = Sed

FLAGS = -Werror -Wextra -Wall -std=c++98

SRCS = main.cpp

OBJS = ${SRCS:.cpp=.o}

RM = rm -rf

CC = c++

all:${Arev}

${Arev}: 	${OBJS}
		${CC} ${FLAGS} -o ${Arev} ${OBJS} 

clean: 
		${RM} ${OBJS}

fclean: clean
		${RM} ${Arev}

re: fclean all

